title: Currency Exchange Rates
description: Widget that displays the current Canadian Dollar (CAD) exchange rate against USD and EUR, with a last-synced timestamp. This can be re-configured for any currency available in the Exchangerate-API.
author: jshields-ca